# Generated by Django 3.1.4 on 2020-12-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20201225_0842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
