# Generated by Django 3.1.4 on 2020-12-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20201225_1448"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="intro",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
