# Generated by Django 3.1.4 on 2020-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20201226_1603"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(blank=True, upload_to="profile_image"),
        ),
    ]
