# Generated by Django 3.1.4 on 2020-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20201227_1523"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_id",
            field=models.IntegerField(null=True),
        ),
    ]
